stages:
    - dependencies
    - build

install_dependencies:
    image: node:12-alpine
    stage: dependencies
    script:
        - npm install
    only:
        - main
    cache:
      key:
        files:
          - package-lock.json
      paths:
        - node_modules

Build:
    image: node:12-alpine
    stage: build
    script:
        - npm link @angular/cli
        - npm run build --prod
    only:
        - main

#npm run build don't put base-href, just set locally
#because there are no /projectName/ on gitlab runner folder
