stages:
    - dependencies
    - build

install_dependencies:
    image: node:12-alpine
    stage: dependencies
    script:
        - npm install
    only:
        - main
    cache:
      key:
        files:
          - package-lock.json
      paths:
        - node_modules

Build:
    image: node:12-alpine
    stage: build
    script:
        - npm link @angular/cli
        - npm run build --prod --base-href /tinder-like-app/
    only:
        - main
