#npm run build don't put base-href, just set locally
#because there are no /projectName/ on gitlab runner folder

#below is for gitlab CI runner and school-server-runner

#default runner -> gitlab share runner
#close share runnder and group runner and redirect to your own machine gitlab runner
#can modify runner to untagged run script

#cache or artifacts is to store this job's(pipeline) specific result
#to next job
#every end of a stage will remove the file it install

stages:
  - dependencies
  - build
  - CD

install_dependencies:
  stage: dependencies
  script:
      - npm install
  only:
      - main
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

Build:
  stage: build
  script:
      - npm link @angular/cli
      - ng build --prod --base-href /tinder-like-app-gitlab/
  only:
      - main
  artifacts:
    paths:
      - dist/

Pull:
  stage: CD
  script:
    - echo "just pull to local server"
  tags:
    - school-server-runner
